spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckPath: /consul/health
        healthCheckInterval: 5s
        instance-id: consul-consumer
  application:
    name: consul-consumer
server:
  port: 2226