spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/agricultureY/springcloud-master.git
          search-paths: config-repo
          username:
          password:

server:
  port: 7075
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka


