server:
  port: 9011
spring:
  application:
    name: trace-product
  zipkin:
    base-url: http://127.0.0.1:9016
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug    #设置日志级别
