server:
  port: 7075

management:
  port: 7078

spring:
  application:
    name: turbine

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka/

turbine:
  app-config: eureka-consumer-hystrix-demotion     #指定需要收集监控信息的服务名
  cluster-name-expression: new String("default") #指定集群名称，当服务数量非常多的时候，可以启动多个turbine服务来构建不同的聚合集群，只需要在Hystrix Stream的URL中通过cluster参数来指定
  combine-host-port: true                        #参数设置为true，可以让同一主机上的服务通过主机名与端口号的组合来进行区分，默认情况下会以host来区分不同的服务，这会使得在本地调试的时候，本机上的不同服务聚合成一个服务来统计。
