server:
  port: 9099
spring:
  application:
    name: order-server
  #Redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 1024
      max-idle: 50
      max-wait: 10000
      min-idle: 10000
# 限流大小
redis:
  limit: 1




