spring:
  application:
    name: config-client
  cloud:
    config:
      uri: http://127.0.0.1:7071/
      profile: dev
      label: master

server:
  port: 7072

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka
