server:
  port: 9022

spring:
  application:
    name: zipkin-stream-product

 #rabbitmq配置
  rabbitmq:
    host: 127.0.0.1
    port : 5672
    username: guest
    password: guest
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1111/eureka

